src/Entity/Livre.php
<?php

namespace App\Entity;

use App\Repository\LivreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=LivreRepository::class)
 */
class Livre
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("\97[89][- ]?[0-9]{1,5}[- ]?[0-9]+[- ]?[0-9]+[- ]?[0-9]$/")
     */
    private $isbn;

    /**
     * @ORM\Column(type="integer")
     */
    private $nombre_pages;

    /**
     * @ORM\Column(type="date")
     */
    private $date_parution;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(
     *             min = 0,
     *             max = 20,
     *             notInRangeMessage= "La valeur doit etre situer entre {{min}} et {{max}} "
     * )
     */
    private $note;

    /**
     * @ORM\ManyToMany(targetEntity=Autheur::class, inversedBy="livres")
     */
    private $autheurs;

    /**
     * @ORM\ManyToMany(targetEntity=Genre::class, inversedBy="livres")
     */
    private $genres;

    public function __construct()
    {
        $this->autheurs = new ArrayCollection();
        $this->genres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getIsbn(): ?string
    {
        return $this->isbn;
    }

    public function setIsbn(string $isbn): self
    {
        $this->isbn = $isbn;

        return $this;
    }

    public function getNombrePages(): ?int
    {
        return $this->nombre_pages;
    }

    public function setNombrePages(int $nombre_pages): self
    {
        $this->nombre_pages = $nombre_pages;

        return $this;
    }

    public function getDateParution(): ?\DateTimeInterface
    {
        return $this->date_parution;
    }

    public function setDateParution(\DateTimeInterface $date_parution): self
    {
        $this->date_parution = $date_parution;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(int $note): self
    {
        $this->note = $note;

        return $this;
    }

    /**
     * @return Collection|Autheur[]
     */
    public function getAutheurs(): Collection
    {
        return $this->autheurs;
    }

    public function addAutheur(Autheur $autheur): self
    {
        if (!$this->autheurs->contains($autheur)) {
            $this->autheurs[] = $autheur;
        }

        return $this;
    }

    public function removeAutheur(Autheur $autheur): self
    {
        $this->autheurs->removeElement($autheur);

        return $this;
    }

    /**
     * @return Collection|Genre[]
     */
    public function getGenres(): Collection
    {
        return $this->genres;
    }

    public function addGenre(Genre $genre): self
    {
        if (!$this->genres->contains($genre)) {
            $this->genres[] = $genre;
        }

        return $this;
    }

    public function removeGenre(Genre $genre): self
    {
        $this->genres->removeElement($genre);

        return $this;
    }
    public function __toString(){
        return $this->titre;
    }
}

src/Form/LivreType.php
<?php

namespace App\Form;

use App\Entity\Livre;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;

class LivreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ->add('isbn',TextType::class,[
            'label' => 'ISBN 13',
            'attr'  => ['class' => 'form-control my-3']
        ])
        ->add('titre',TextType::class,[
            'label' => 'Titre',
            'attr'  => ['class' => 'form-control my-3']
        ])
        ->add('nombre_pages',null,[
            'label' => 'Nombre de pages',
            'attr'  => ['class' => 'form-control my-3']
        ])
        ->add('autheurs',null,[
            'attr'  => ['class' => 'form-control my-3']
        ])
        ->add('genres',null,[
            'attr'  => ['class' => 'form-control my-3']
        ])
        ->add('date_parution',DateType::class,[
            'label' => 'Date de parution',
            'widget' => 'single_text',
            'attr' => ['class' => 'form-control my-3']
            ])
        ->add('note',null,[
                'attr' => ['class' => 'form-control my-3']
                ])
        
       
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Livre::class,
        ]);
    }
}

src/Controller/LivreController.php
<?php

namespace App\Controller;

use App\Entity\Livre;
use App\Form\LivreType;
use App\Repository\LivreRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
// Include paginator interface
use Knp\Component\Pager\PaginatorInterface;

/**
 * @Route("/livre")
 */
class LivreController extends AbstractController
{
    /**
     * @Route("/", name="livre_index", methods={"GET"})
     */
    public function index(Request $request,LivreRepository $livreRepository, PaginatorInterface $paginator): Response
    {
        $livres=$livreRepository->findAll();
        $livres = $paginator->paginate(
            $livres, 
            $request->query->getInt('page', 1),
            8/*limit per page*/
        );
        return $this->render('livre/index.html.twig', [
            'livres' => $livres,
        ]);
    }

    /**
     * @Route("/new", name="livre_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $livre = new Livre();
        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($livre);
            $entityManager->flush();

            return $this->redirectToRoute('livre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('livre/new.html.twig', [
            'livre' => $livre,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="livre_show", methods={"GET"})
     */
    public function show(Livre $livre): Response
    {
        return $this->render('livre/show.html.twig', [
            'livre' => $livre,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="livre_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Livre $livre, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('livre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('livre/edit.html.twig', [
            'livre' => $livre,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="livre_delete", methods={"POST"})
     */
    public function delete(Request $request, Livre $livre, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$livre->getId(), $request->request->get('_token'))) {
            $entityManager->remove($livre);
            $entityManager->flush();
        }

        return $this->redirectToRoute('livre_index', [], Response::HTTP_SEE_OTHER);
    }
    /**
     * @Route("/search/{motCle}", name="livre_search", methods={"GET"})
     */
    public function chercherMotCle(String $motCle,LivreRepository $lr){
      $livres = $lr->findByTitre($motCle);
      return $this->render('livre/search.html.twig', [
        'livres' => $livres,
    ]);
    }
}

templates/livre/_delete_form.html.twig
<form method="post" action="{{ path('livre_delete', {'id': livre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ livre.id) }}">
       <button class="btn btn-danger"><i class="bi bi-file-x"></i>delete</button>

</form>

templates/livre/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success p-2 w-100 text-center">{{ button_label|default('save') }}<i class="bi bi-person-plus-fill"></i></button>
{{ form_end(form) }}

templates/livre/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Livre{% endblock %}

{% block body %}
    <div class="container-fluid p-4 ">
<div class="row">
<div class="col-md-3"></div>
<div class="col-md-6 border border-5 bg-light p-4 ">
    <h3 class="mb-4 text-center">Edit book :</h3>

    {{ include('livre/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('livre_index') }}">back to list</a>

    </div></div></div>
{% endblock %}

templates/livre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livre index{% endblock %}
{% block stylesheets %}
<style>
#ab{
    border-radius : 10px;
    
    margin-top : 60px;
}
#lb{
    font-size : 15px;
}
</style>
{% endblock %}
{% block javascripts %}
<script>
    
    function search(e){
const motCle= document.getElementById("motCle");
e.preventDefault();
const mot = motCle.value;
window.location.replace('/livre/search/'+mot);
    }
    </script>
{% endblock %}
{% block body %}        
<div class="container-fluid p-3 bg-light">
<div class="row p-3">
<div class="col-md-3 bg-light border border-5 mr-4 pt-5 h-75 pb-5 bg-white border-secondary" id="ab">
<form action="" class="form" onsubmit="search(event)" >
<div class="form-group text-center">
<label for="" class="mb-3  fw-bold " div="lb">Recherche par mot clé :</label>
<input type="text" class="form-control mb-3" placeholder="mot clé" id="motCle">
</div >
<div class="form-group">
<button class="form-control btn btn-outline-success"   type="submit" id="mc">search</button>
</div>
</form>

</div>
<div class="col-md-9">
    <h1 class="text-center mb-4">List of books :</h1>

    <table class="table table-striped ">
        <thead class="bg-dark text-white " >
            <tr>
                <th>Titre</th>
                <th>Nombre_pages</th>
                <th>Date_parution</th>
                <th>Note</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for livre in livres %}
            <tr>
                <td>{{ livre.titre }}</td>
                <td>{{ livre.nombrePages }}</td>
                <td>{{ livre.dateParution ? livre.dateParution|date('Y-m-d') : '' }}</td>
                <td>{{ livre.note }}</td>
                <td>
                     
                                       <form class="p-2" method="post" action="{{ path('livre_delete', {'id': livre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                                              <a href="{{ path('livre_show', {'id': livre.id}) }}" class="btn btn-warning"><i class="bi bi-display"></i></a>
                                            {% if is_granted('ROLE_ADMIN') %} 
                                             <a href="{{ path('livre_edit', {'id': livre.id}) }}" class="btn btn-success"><i class="bi bi-pen"></i></a>
                                                 <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ livre.id) }}">
                                                  <button class="btn btn-danger"><i class="bi bi-file-x"></i></button>
                                           {% endif %}
                                           </form>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="d-flex justify-content-center">{{ knp_pagination_render(livres,'pagination_page.html.twig') }}</div> 

</div></div></div>
    <a href="{{ path('livre_new') }}">Create new</a>
    
{% endblock %}

templates/livre/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Livre{% endblock %}

{% block body %}
<div class="container-fluid p-4 ">
<div class="row">
<div class="col-md-3"></div>
<div class="col-md-6 border border-5 bg-light p-4 ">
    <h3 class="mb-4 text-center">Create new book :</h3>

    {{ include('livre/_form.html.twig') }}

    <a href="{{ path('livre_index') }}">back to list</a>
    </div></div></div>
{% endblock %}

templates/livre/search.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les détails du Livre{% endblock %}

{% block body %}
<div class="container-fluid p-3 ">
<div class="row p-3">
<div class="col-md-1"></div>
<div class="col-md-10">
    <h1 class="text-center mb-4">the search result :</h1>

    <table class="table table-striped">
        <thead class="bg-dark text-white">
            <tr>
                <th>Titre</th>
                 <th>Isbn</th>
                  <th>nombres des pages</th>
                 <th>Date_parution</th>
                 <th>Note</th>
            </tr>
             </thead>
              </tbody>
            {% for livre in livres %}
            <tr>
               <td>{{ livre.titre }}</td>
                <td>{{ livre.isbn }}</td>
                <td>{{ livre.nombrePages }}</td>
                <td>{{ livre.dateParution ? livre.dateParution|date('Y-m-d') : '' }}</td>
                <td>{{ livre.note }}</td>
            </tr>
           {% endfor %}
        </tbody>
    </table>
</div></div></div>
    <a href="{{ path('livre_index') }}">back to list</a>

    
{% endblock %}

templates/livre/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livre{% endblock %}

{% block body %}
  <div class="container-fluid p-4 ">
<div class="row">
<div class="col-md-2"></div>
<div class="col-md-8  p-3  bg-light text-center border border-5">
    <h3 class="mb-4 text-center">Book details :</h3>
    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ livre.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ livre.titre }}</td>
            </tr>
            <tr>
                <th>Isbn</th>
                <td>{{ livre.isbn }}</td>
            </tr>
            <tr>
                <th>Nombre_pages</th>
                <td>{{ livre.nombrePages }}</td>
            </tr>
            <tr>
                <th>Date_parution</th>
                <td>{{ livre.dateParution ? livre.dateParution|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Note</th>
                <td>{{ livre.note }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('livre_index') }}">back to list</a>

  
    </div></div></div>
{% endblock %}