src/Entity/Autheur.php
<?php

namespace App\Entity;

use App\Repository\AutheurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=AutheurRepository::class)
 */
class Autheur
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $sexe;

    /**
     * @ORM\Column(type="date")
     */
    private $date_naissance;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Country
     */
    private $nationalite;

    /**
     * @ORM\ManyToMany(targetEntity=Livre::class, mappedBy="autheurs")
     */
    private $livres;

    public function __construct()
    {
        $this->livres = new ArrayCollection();
    }
//getters and setters : 
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomPrenom(): ?string
    {
        return $this->nom_prenom;
    }

    public function setNomPrenom(string $nom_prenom): self
    {
        $this->nom_prenom = $nom_prenom;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getNationalite(): ?string
    {
        return $this->nationalite;
    }

    public function setNationalite(string $nationalite): self
    {
        $this->nationalite = $nationalite;

        return $this;
    }

    /**
     * @return Collection|Livre[]
     */
    public function getLivres(): Collection
    {
        return $this->livres;
    }

    public function addLivre(Livre $livre): self
    {
        if (!$this->livres->contains($livre)) {
            $this->livres[] = $livre;
            $livre->addAutheur($this);
        }

        return $this;
    }

    public function removeLivre(Livre $livre): self
    {
        if ($this->livres->removeElement($livre)) {
            $livre->removeAutheur($this);
        }

        return $this;
    }
    public function __toString(){
        return $this->nom_prenom;
    }

    
}

src/Form/AutheurType.php
<?php

namespace App\Form;

use App\Entity\Autheur;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateType;

class AutheurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_prenom',TextType::class,[
                'label' => 'Nom et Prenom',
                'attr'  => ['class' => 'form-control my-3']
            ])
            ->add('sexe',ChoiceType::class,[
                'choices' => [
                    'Feminin' => 'F',
                    'Masculin' => 'M'
                ],
                'attr' => ['class' => 'form-control my-3']
            ])
            ->add('date_naissance',DateType::class,[
             'label' => 'Date de naissance',
             'widget' => 'single_text',
            'attr' => ['class' => 'form-control my-3']
            ])
            ->add('nationalite',TextType::class,['attr' => ['class' => 'form-control my-3']])
            ->add('livres',null,[
                'label' => 'Livres',
                'attr'  => ['class' => 'form-control my-3']
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Autheur::class,
        ]);
    }
}

src/Controller/AutheurController.php
<?php

namespace App\Controller;

use App\Entity\Autheur;
use App\Form\AutheurType;
use App\Repository\AutheurRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/autheur")
 */
class AutheurController extends AbstractController
{
    /**
     * @Route("/", name="autheur_index", methods={"GET"})
     */
    public function index(AutheurRepository $autheurRepository): Response
    {
        return $this->render('autheur/index.html.twig', [
            'autheurs' => $autheurRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="autheur_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $autheur = new Autheur();
        $form = $this->createForm(AutheurType::class, $autheur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($autheur);
            $entityManager->flush();

            return $this->redirectToRoute('autheur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('autheur/new.html.twig', [
            'autheur' => $autheur,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="autheur_show", methods={"GET"})
     */
    public function show(Autheur $autheur): Response
    {
        return $this->render('autheur/show.html.twig', [
            'autheur' => $autheur,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="autheur_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Autheur $autheur, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AutheurType::class, $autheur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('autheur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('autheur/edit.html.twig', [
            'autheur' => $autheur,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="autheur_delete", methods={"POST"})
     */
    public function delete(Request $request, Autheur $autheur, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$autheur->getId(), $request->request->get('_token'))) {
            $entityManager->remove($autheur);
            $entityManager->flush();
        }

        return $this->redirectToRoute('autheur_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/autheur/_delete_form.html.twig
<form method="post" action="{{ path('autheur_delete', {'id': autheur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ autheur.id) }}">
    <button class="btn btn-danger"><i class="bi bi-file-x"></i>delete</button>
</form>

templates/autheur/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success p-2 w-100 text-center">{{ button_label|default('save') }}<i class="bi bi-person-plus-fill"></i></button>
{{ form_end(form) }}

templates/autheur/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Autheur{% endblock %}

{% block body %}
     <div class="container-fluid p-4 ">
<div class="row">
<div class="col-md-3"></div>
<div class="col-md-6 border border-5 bg-light p-4 ">
    <h3 class="mb-4 text-center">Edit author :</h3>

    {{ include('autheur/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('autheur_index') }}">back to list</a>

    
    </div></div></div>
{% endblock %}

templates/autheur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Autheur index{% endblock %}

{% block body %}
    <div class="container-fluid p-3">
<div class="row p-3">
<div class="col-md-12">
    <h1 class="text-center mb-4">List of Authors :</h1>

    <table class="table table-striped">
        <thead class="bg-dark text-white">
            <tr class="text-center">
                <th>Nom_prenom</th>
                <th>Date_naissance</th>
                <th>Nationalite</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for autheur in autheurs %}
            <tr class="text-center">
                <td>{{ autheur.nomPrenom }}</td>
                <td>{{ autheur.dateNaissance ? autheur.dateNaissance|date('Y-m-d') : '' }}</td>
                <td>{{ autheur.nationalite }}</td>
                <td>
                                       <form class="p-2" method="post" action="{{ path('autheur_delete', {'id': autheur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                                             <a href="{{ path('autheur_show', {'id': autheur.id}) }}" class="btn btn-warning"><i class="bi bi-display"></i></a>
                                              {% if is_granted('ROLE_ADMIN') %}<a href="{{ path('autheur_edit', {'id': autheur.id}) }}" class="btn btn-success"><i class="bi bi-pen"></i></a>
                                                 <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ autheur.id) }}">
                                                  <button class="btn btn-danger"><i class="bi bi-file-x"></i></button>{% endif %}
                                           </form>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table></div></div></div>

    <a href="{{ path('autheur_new') }}">Create new</a>
{% endblock %}

templates/autheur/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Autheur{% endblock %}

{% block body %}
    <div class="container-fluid p-4 ">
<div class="row">
<div class="col-md-3"></div>
<div class="col-md-6 border border-5 bg-light p-4 ">
    <h3 class="mb-4 text-center">Create new author :</h3>

    {{ include('autheur/_form.html.twig') }}

    <a href="{{ path('autheur_index') }}">back to list</a>
    </div> </div> </div>
{% endblock %}

templates/autheur/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Autheur{% endblock %}

{% block body %}
     <div class="container-fluid p-4 ">
<div class="row">
<div class="col-md-2"></div>
<div class="col-md-8  p-3  bg-light text-center border border-5">
    <h3 class="mb-4 text-center">Author details :</h3>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ autheur.id }}</td>
            </tr>
            <tr>
                <th>Nom_prenom</th>
                <td>{{ autheur.nomPrenom }}</td>
            </tr>
            <tr>
                <th>Sexe</th>
                <td>{{ autheur.sexe }}</td>
            </tr>
            <tr>
                <th>Date_naissance</th>
                <td>{{ autheur.dateNaissance ? autheur.dateNaissance|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Nationalite</th>
                <td>{{ autheur.nationalite }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('autheur_index') }}">back to list</a>

   
    </div></div></div>
{% endblock %}